# Library and data import

In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor

from scipy import stats

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

sns.set()

In [ ]:
# Pull dataset from Kaggle

!pip install kaggle > ignore.txt
!echo '{"username":"sean2000","key":"cb63f8ed9d54a5005aebbec6489b2a4f"}' > ./kaggle.json

ERROR: Operation cancelled by user

In [ ]:
# It seems you may need to run this twice

!cp ./kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

#!kaggle datasets files -v cdc/behavioral-risk-factor-surveillance-system
!kaggle datasets download -f 2015.csv -w cdc/behavioral-risk-factor-surveillance-system
!unzip ./2015.csv.zip
!rm ./2015.csv.zip

Downloading 2015.csv.zip to .
 93% 73.0M/78.3M [00:01<00:00, 69.3MB/s]
100% 78.3M/78.3M [00:01<00:00, 76.0MB/s]
Archive:  ./2015.csv.zip
replace 2015.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
# Optional cell for downloading all available years of data from CDC
'''
!kaggle datasets download -f 2011.csv -w cdc/behavioral-risk-factor-surveillance-system
!unzip ./2011.csv.zip
!rm ./2011.csv.zip
!kaggle datasets download -f 2012.csv -w cdc/behavioral-risk-factor-surveillance-system
!unzip ./2012.csv.zip
!rm ./2012.csv.zip
!kaggle datasets download -f 2013.csv -w cdc/behavioral-risk-factor-surveillance-system
!unzip ./2013.csv.zip
!rm ./2013.csv.zip
!kaggle datasets download -f 2014.csv -w cdc/behavioral-risk-factor-surveillance-system
!unzip ./2014.csv.zip
!rm ./2014.csv.zip
'''

'\n!kaggle datasets download -f 2011.csv -w cdc/behavioral-risk-factor-surveillance-system\n!unzip ./2011.csv.zip\n!rm ./2011.csv.zip\n!kaggle datasets download -f 2012.csv -w cdc/behavioral-risk-factor-surveillance-system\n!unzip ./2012.csv.zip\n!rm ./2012.csv.zip\n!kaggle datasets download -f 2013.csv -w cdc/behavioral-risk-factor-surveillance-system\n!unzip ./2013.csv.zip\n!rm ./2013.csv.zip\n!kaggle datasets download -f 2014.csv -w cdc/behavioral-risk-factor-surveillance-system\n!unzip ./2014.csv.zip\n!rm ./2014.csv.zip\n'

In [ ]:
#Reading datasets
df = pd.read_csv("2015.csv")

In [ ]:
# rows and columns of df 
df.shape

(441456, 330)

In [ ]:
# check the data's format 
pd.set_option('display.max_columns', 400)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18.0,10.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,70.0,178.0,12701.0,4018.0,4.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.700000e+01,33.0,6.700000e+01,33.0,17.0,100.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,50.0,217.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,4.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,2.0,6.0,1.0,2.0,NaN,2.0,2.0,3.0,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,1.0,28.781560,NaN,NaN,NaN,NaN,9.0,NaN,108.060903,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,52.0,4.0,68.0,173.0,7484.0,2509.0,3.0,2.0,1.0,4.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,7.000000e+00,17.0,7.000000e+00,29.0,29.0,13.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,24.0,78.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,5.397605e-79,2876.0,493.0,1.0,5.397605e-79,60.0,60.0,2800.0,2800.0,168.0,5.397605e-79,5.397605e-79,5.397605e-79,168.0,5.397605e-79,168.0,5.397605e-79,5.397605e-79,5.397605e-79,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,2.0
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88.0,88.0,1.0,2.0,2.0,1.0,3.0,NaN,1.0,1.0,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,2.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,1.0,0.614125,255.264797,2.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,71.0,6.0,71.0,180.0,7167.0,2204.0,2.0,1.0,1.0,2.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,2173.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,30.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,67.0,170.0,8165.0,2819.0,3.0,2.0,2.0,2.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,100.0,5.397605e-79,3.0,3.0,14.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,100.0,20.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,9.0
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88.0,30.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,1.0,5.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,9.0,NaN,258.682223,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,61.0,5.0,64.0,163.0,6441.0,2437.0,2.0,1.0,1.0,3.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,200.0,4.300000e+01,57.0,33.0,67.0,1.000000e+00,5.397605e-79,5.397605e-79,1.000000e+00,NaN,200.0,9.0,1.0,1.0,1.0,1.000000e+00,5.397605e-79,2.0,NaN,NaN,2543.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0

In [ ]:
# checking value types and missing data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441456 entries, 0 to 441455
Columns: 330 entries, _STATE to _AIDTST3
dtypes: float64(323), object(7)
memory usage: 1.1+ GB

# Data cleaning

In [ ]:
# deleting the columns with categorical data types, as these attributes have been deemed unimportant 
del df['IDATE']
del df['IMONTH']
del df['IDAY']
del df['IYEAR']
del df['PCDMDECN']
del df['EXACTOT1']
del df['EXACTOT2']

In [ ]:
# checking value types and missing data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441456 entries, 0 to 441455
Columns: 323 entries, _STATE to _AIDTST3
dtypes: float64(323)
memory usage: 1.1 GB

In [ ]:
# checking how many missing values each attribute has 
# notice that only 79/323 attributes have no missing values
df.isnull().sum().sort_values()

_STATE           0
_CHLDCNT         0
_EDUCAG          0
_INCOMG          0
_SMOKER3         0
             ...
COLGHOUS    441411
PAINACT2    441456
QLHLTH2     441456
QLSTRES2    441456
QLMENTL2    441456
Length: 323, dtype: int64

In [ ]:
# select important columns
df_important = df[['_MICHD',
                   '_RFHYPE5',
                   'TOLDHI2',
                   '_CHOLCHK', 
                   '_BMI5', 
                   'SMOKE100', 
                   'CVDSTRK3',
                   'DIABETE3', 
                   '_TOTINDA', 
                   '_FRTLT1',
                   '_VEGLT1', 
                   '_RFDRHV5', 
                   'HLTHPLN1',
                   'MEDCOST', 
                   'GENHLTH',
                   'MENTHLTH',
                   'PHYSHLTH',
                   'DIFFWALK', 
                   'SEX',
                   '_AGEG5YR',
                   'EDUCA',
                   'INCOME2' ]]
df_important.shape

(441456, 22)

In [ ]:
# dropping any remaining missing values 
df_important = df_important.dropna()
df_important.shape

(343606, 22)

In [ ]:
# refering to the dataset, 2 means did not have so 0 is a better indicator
df_important['_MICHD'] = df_important['_MICHD'].replace({2: 0})
df_important._MICHD.unique()

array([0., 1.])

In [ ]:
# 1 means no high blood pressure so change it to 0
# 2 means high blood pressure so change it to 1 
# 9 means refused so eliminate
df_important['_RFHYPE5'] = df_important['_RFHYPE5'].replace({1:0, 2:1})
df_important = df_important[df_important._RFHYPE5 != 9]
df_important._RFHYPE5.unique()

array([1., 0.])

In [ ]:
# 2 means doesn't have it so change to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['TOLDHI2'] = df_important['TOLDHI2'].replace({2:0})
df_important = df_important[df_important.TOLDHI2 != 7]
df_important = df_important[df_important.TOLDHI2 != 9]
df_important.TOLDHI2.unique()

array([1., 0.])

In [ ]:
# Three means cholesterol hasn't been checked in the past 5 years so change to zero
# 2 means XXX so change to 0
# 9 means refused so eliminate
df_important['_CHOLCHK'] = df_important['_CHOLCHK'].replace({3:0,2:0})
df_important = df_important[df_important._CHOLCHK != 9]
df_important._CHOLCHK.unique()

array([1., 0.])

In [ ]:
# In the dataset BMI is x100, so divide by 100
df_important['_BMI5'] = df_important['_BMI5'].div(100).round(0)
df_important._BMI5.unique()

array([40., 25., 28., 24., 27., 30., 26., 23., 34., 33., 21., 22., 31.,
       38., 20., 19., 32., 46., 41., 37., 36., 29., 35., 18., 54., 45.,
       39., 47., 43., 55., 49., 42., 17., 16., 48., 44., 50., 59., 15.,
       52., 53., 57., 51., 14., 58., 63., 61., 56., 60., 74., 62., 64.,
       13., 66., 73., 65., 68., 85., 71., 84., 67., 70., 82., 79., 92.,
       72., 88., 96., 81., 12., 77., 95., 75., 91., 69., 76., 87., 89.,
       83., 98., 86., 80., 90., 78., 97.])

In [ ]:
# 2 means don't have so turn to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['SMOKE100'] = df_important['SMOKE100'].replace({2:0})
df_important = df_important[df_important.SMOKE100 != 7]
df_important = df_important[df_important.SMOKE100 != 9]
df_important.SMOKE100.unique()

array([1., 0.])

In [ ]:
# 2 means don't have so turn to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['CVDSTRK3'] = df_important['CVDSTRK3'].replace({2:0})
df_important = df_important[df_important.CVDSTRK3 != 7]
df_important = df_important[df_important.CVDSTRK3 != 9]
df_important.CVDSTRK3.unique()

array([0., 1.])

In [ ]:
# Change so 0 = no long term diabetes, 1 = pre-diabetic, 2 = has diabetes
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['DIABETE3'] = df_important['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
df_important = df_important[df_important.DIABETE3 != 7]
df_important = df_important[df_important.DIABETE3 != 9]
df_important.DIABETE3.unique()

array([0., 2., 1.])

In [ ]:
# 2 means no physical activity so change to 0
# 9 means refused so eliminate
df_important['_TOTINDA'] = df_important['_TOTINDA'].replace({2:0})
df_important = df_important[df_important._TOTINDA != 9]
df_important._TOTINDA.unique()

array([0., 1.])

In [ ]:
# 2 means no fruit so change to 0
# 9 means refused so eliminate
df_important['_FRTLT1'] = df_important['_FRTLT1'].replace({2:0})
df_important = df_important[df_important._FRTLT1 != 9]
df_important._FRTLT1.unique()

array([0., 1.])

In [ ]:
# 2 means no vegetables so change to 0
# 9 means refused so eliminate
df_important['_VEGLT1'] = df_important['_VEGLT1'].replace({2:0})
df_important = df_important[df_important._VEGLT1 != 9]
df_important._VEGLT1.unique()

array([1., 0.])

In [ ]:
# 1 means no heavy drinking so change to 0
# 2 means heavy drinking so change to 1
# 9 means refused so eliminate
df_important['_RFDRHV5'] = df_important['_RFDRHV5'].replace({1:0, 2:1})
df_important = df_important[df_important._RFDRHV5 != 9]
df_important._RFDRHV5.unique()

array([0., 1.])

In [ ]:
# 2 means no health care access so change to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['HLTHPLN1'] = df_important['HLTHPLN1'].replace({2:0})
df_important = df_important[df_important.HLTHPLN1 != 7]
df_important = df_important[df_important.HLTHPLN1 != 9]
df_important.HLTHPLN1.unique()

array([1., 0.])

In [ ]:
# 2 means no so change to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['MEDCOST'] = df_important['MEDCOST'].replace({2:0})
df_important = df_important[df_important.MEDCOST != 7]
df_important = df_important[df_important.MEDCOST != 9]
df_important.MEDCOST.unique()

array([0., 1.])

In [ ]:
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important = df_important[df_important.GENHLTH != 7]
df_important = df_important[df_important.GENHLTH != 9]
df_important.GENHLTH.unique()

array([5., 3., 2., 4., 1.])

In [ ]:
# 88 means no bad mental health days so change to 0 
# 77 means don't know so eliminate
# 99 means refused so eliminate
df_important['MENTHLTH'] = df_important['MENTHLTH'].replace({88:0})
df_important = df_important[df_important.MENTHLTH != 77]
df_important = df_important[df_important.MENTHLTH != 99]
df_important.MENTHLTH.unique()

array([18.,  0., 30.,  3.,  5., 15., 10.,  6., 20.,  2., 25.,  1., 29.,
        4.,  7.,  8., 21., 14., 26.,  9., 16., 28., 11., 12., 24., 17.,
       13., 23., 27., 19., 22.])

In [ ]:
# 88 means no bad mental health days so change to 0 
# 77 means don't know so eliminate
# 99 means refused so eliminate
df_important['PHYSHLTH'] = df_important['PHYSHLTH'].replace({88:0})
df_important = df_important[df_important.PHYSHLTH != 77]
df_important = df_important[df_important.PHYSHLTH != 99]
df_important.PHYSHLTH.unique()

array([15.,  0., 30.,  2., 14., 28.,  7., 20.,  3., 10.,  1.,  5., 17.,
        4., 19.,  6., 21., 12.,  8., 25., 27., 22., 29., 24.,  9., 16.,
       18., 23., 13., 26., 11.])

In [ ]:
# 2 means no so change to 0
# 7 means don't know so eliminate
# 9 means refused so eliminate
df_important['DIFFWALK'] = df_important['DIFFWALK'].replace({2:0})
df_important = df_important[df_important.DIFFWALK != 7]
df_important = df_important[df_important.DIFFWALK != 9]
df_important.DIFFWALK.unique()

array([1., 0.])

In [ ]:
# 2 means female so change to 0 (male is 1)
df_important['SEX'] = df_important['SEX'].replace({2:0})
df_important.SEX.unique()

array([0., 1.])

In [ ]:
# 14 means don't know or is missing so eliminate
df_important = df_important[df_important._AGEG5YR != 14]
df_important._AGEG5YR.unique()

array([ 9.,  7., 11., 10., 13.,  8.,  4.,  6.,  2., 12.,  5.,  1.,  3.])

In [ ]:
# 9 means refused so eliminate
df_important = df_important[df_important.EDUCA != 9]
df_important.EDUCA.unique()

array([4., 6., 3., 5., 2., 1.])

In [ ]:
# 77 means don't know so eliminate
# 99 means refused so eliminate
df_important = df_important[df_important.INCOME2 != 77]
df_important = df_important[df_important.INCOME2 != 99]
df_important.INCOME2.unique()

array([3., 1., 8., 6., 4., 7., 2., 5.])

Data exploration

In [ ]:
df_important.shape

(253680, 22)

In [ ]:
df_important.head()

,_MICHD,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,DIABETE3,_TOTINDA,_FRTLT1,_VEGLT1,_RFDRHV5,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEX,_AGEG5YR,EDUCA,INCOME2
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
3,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
5,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
6,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [ ]:
# Use more understandable column header 
df_important = df_important.rename(columns = {'_MICHD':'HeartDiseaseorAttack', 
                                         '_RFHYPE5':'HighBP',  
                                         'TOLDHI2':'HighChol',
                                          '_CHOLCHK':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke',
                                          'DIABETE3':'Diabetes', 
                                         '_TOTINDA':'PhysActivity', 
                                         '_FRTLT1':'Fruits', 
                                         '_VEGLT1':"Veggies", 
                                         '_RFDRHV5':'HvyAlcoholConsump', 
                                         'HLTHPLN1':'AnyHealthcare', 
                                         'MEDCOST':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 
                                         'MENTHLTH':'MentHlth', 
                                         'PHYSHLTH':'PhysHlth', 
                                         'DIFFWALK':'DiffWalk', 
                                         'SEX':'Sex', 
                                         '_AGEG5YR':'Age',
                                         'EDUCA':'Education', 
                                         'INCOME2':'Income' })

In [ ]:
df_important.to_csv('heart_indicators_clean_data.csv', sep = ",", index = False)

In [ ]:
store = pd.HDFStore('store.h5')
store['df'] = df_important